const ACCOUNT_STATUS = {
  NO_METAMASK: "NO_METAMASK",
  WRONG_NET: "WRONG_NET",
  LOCKED_ACCOUNT: "LOCKED_ACCOUNT",
  UN_REGISTER: "UN_REGISTER",
  HAS_LOGIN: "HAS_LOGIN"
};

export { ACCOUNT_STATUS };
